Parameters Makro @pack has been renamed to @pack!
OrdinaryDiffEq wouldn't compile on a fresh julia 1.0 env.
```
ERROR: LoadError: LoadError: LoadError: UndefVarError: @pack not defined
Stacktrace:
 [1] top-level scope
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /home/jonas/.julia/dev/OrdinaryDiffEq/src/OrdinaryDiffEq.jl:1
 [6] top-level scope at none:0
 [7] include at ./boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] _require(::Base.PkgId) at ./loading.jl:950
 [10] require(::Base.PkgId) at ./loading.jl:852
 [11] macro expansion at ./logging.jl:311 [inlined]
 [12] require(::Module, ::Symbol) at ./loading.jl:834
in expression starting at /home/jonas/.julia/dev/OrdinaryDiffEq/src/perform_step/exponential_rk_perform_step.jl:1434
in expression starting at /home/jonas/.julia/dev/OrdinaryDiffEq/src/perform_step/exponential_rk_perform_step.jl:1416
in expression starting at /home/jonas/.julia/dev/OrdinaryDiffEq/src/OrdinaryDiffEq.jl:98
```

This seems to fix it
See https://github.com/mauro3/Parameters.jl/pull/71