WIP: Change to LinearSolve.jl
Currently hits a weird error:

```julia
[ Info: Precompiling OrdinaryDiffEq [1dea7af3-3e70-54e6-95c3-0bf5283fa5ed]
ERROR: LoadError: syntax: SSAValue objects should not occur in an AST
Stacktrace:
  [1] top-level scope
    @ C:\Users\accou\.julia\dev\OrdinaryDiffEq\src\perform_step\rosenbrock_perform_step.jl:27
  [2] include(mod::Module, _path::String)
    @ Base .\Base.jl:418
  [3] include(x::String)
    @ OrdinaryDiffEq C:\Users\accou\.julia\dev\OrdinaryDiffEq\src\OrdinaryDiffEq.jl:4
  [4] top-level scope
    @ C:\Users\accou\.julia\dev\OrdinaryDiffEq\src\OrdinaryDiffEq.jl:148
  [5] include
    @ .\Base.jl:418 [inlined]
  [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base .\loading.jl:1318
  [7] top-level scope
    @ none:1
  [8] eval
    @ .\boot.jl:373 [inlined]
  [9] eval(x::Expr)
    @ Base.MainInclude .\client.jl:453
 [10] top-level scope
    @ none:1
in expression starting at C:\Users\accou\.julia\dev\OrdinaryDiffEq\src\perform_step\rosenbrock_perform_step.jl:27
in expression starting at C:\Users\accou\.julia\dev\OrdinaryDiffEq\src\OrdinaryDiffEq.jl:1
```

@yingboma do you know what could cause that?